USE [master]
GO
/****** Object:  Database [ETicaret]    Script Date: 10.04.2022 23:36:39 ******/
CREATE DATABASE [ETicaret]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ETicaret', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ETicaret.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ETicaret_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ETicaret_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ETicaret] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ETicaret].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ETicaret] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ETicaret] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ETicaret] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ETicaret] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ETicaret] SET ARITHABORT OFF 
GO
ALTER DATABASE [ETicaret] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ETicaret] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ETicaret] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ETicaret] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ETicaret] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ETicaret] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ETicaret] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ETicaret] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ETicaret] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ETicaret] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ETicaret] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ETicaret] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ETicaret] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ETicaret] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ETicaret] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ETicaret] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ETicaret] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ETicaret] SET RECOVERY FULL 
GO
ALTER DATABASE [ETicaret] SET  MULTI_USER 
GO
ALTER DATABASE [ETicaret] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ETicaret] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ETicaret] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ETicaret] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [ETicaret] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'ETicaret', N'ON'
GO
USE [ETicaret]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 10.04.2022 23:36:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryID] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](25) NOT NULL,
	[C_Description] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[OrderDetail]    Script Date: 10.04.2022 23:36:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetail](
	[OrderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Price] [decimal](6, 2) NOT NULL,
	[Quantity] [int] NOT NULL,
 CONSTRAINT [PK_ProductId] PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC,
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Orders]    Script Date: 10.04.2022 23:36:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderId] [int] IDENTITY(1,1) NOT NULL,
	[OrderDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Products]    Script Date: 10.04.2022 23:36:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [nvarchar](50) NOT NULL,
	[Price] [decimal](6, 2) NOT NULL,
	[P_CategoryID] [int] NOT NULL,
	[P_SupplierId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Suppliers]    Script Date: 10.04.2022 23:36:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Suppliers](
	[SupplierId] [int] IDENTITY(1,1) NOT NULL,
	[CompanyName] [nvarchar](50) NOT NULL,
	[Phone] [char](11) NULL,
	[CreatedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplierId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UQ_SupplierId] UNIQUE NONCLUSTERED 
(
	[SupplierId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[OrderDetail] ADD  DEFAULT ((1)) FOR [Quantity]
GO
ALTER TABLE [dbo].[Orders] ADD  DEFAULT (getdate()) FOR [OrderDate]
GO
ALTER TABLE [dbo].[Suppliers] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_OrderId] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Orders] ([OrderId])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_OrderId]
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_ProductId] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([ProductId])
GO
ALTER TABLE [dbo].[OrderDetail] CHECK CONSTRAINT [FK_ProductId]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([P_CategoryID])
REFERENCES [dbo].[Categories] ([CategoryID])
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD FOREIGN KEY([P_SupplierId])
REFERENCES [dbo].[Suppliers] ([SupplierId])
GO
ALTER TABLE [dbo].[OrderDetail]  WITH CHECK ADD CHECK  (([Price]>(0)))
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD CHECK  (([Price]>(0)))
GO
USE [master]
GO
ALTER DATABASE [ETicaret] SET  READ_WRITE 
GO
